### ISSUE TITLE
Remove get() from string class

### ISSUE THREAD

**Issue by tomharmon** [jjones-99/cs4500-sp2020-a1-part2-jones-tam#17]
Could you please remove the `get()` method from string? I can't find any issues where someone requested it, and `get()` is not in the standard spec on chasebish's repo, so the addition of `get()` re-introduces the whole dependency graph of object/string.

**Comment by jjones-99** [comment]
Fixed in a7e4757. Sorry about that. It doesn't really make sense to have a String but no way of getting the String value, but I guess that's out of scope for this assignment.

**Comment by tomharmon** [comment]
thank you! yes i agree about getting the string value, but all of CwC doesn't make much sense anyways so 😅
