### ISSUE TITLE
change bool equals(Object const* obj) to bool equals(Object *obj) in map.h?

### ISSUE THREAD

**Issue by angeliama98** [jjones-99/cs4500-sp2020-a1-part2-jones-tam#19]
If we stay with const for input obj, when I try to compare the object in the map with obj, we will get the following error. 

error: 
      invalid operands to binary expression ('Object' and 'const Object *')

**Comment by jjones-99** [comment]
What’s the context of the error? It might be an issue with your implementation. The const means the pointer can’t be changed in the method, and I can’t see a situation where you’d need to change the pointer in `equals()`. And I think the same signature was working for most teams without such an error.

**Comment by angeliama98** [comment]
You're right. I should cast 'this' instead of 'obj'.

**Comment by jjones-99** [comment]
Awesome, I’m glad it got figured out!
