### ISSUE TITLE
`StrToStrMap` unneccessary

### ISSUE THREAD

**Issue by tomharmon** [jjones-99/cs4500-sp2020-a1-part2-jones-tam#4]
`StrToStrMap` is unneccessary since `Object*` can be casted to `String*`. Please remove

**Comment by jjones-99** [comment]
`StrToStrMap` has been removed. We were originally providing it as a simple wrapper to do the casting for the user and hide those implementation details.

**Comment by tomharmon** [comment]
Sorry, due to [this](https://piazza.com/class/k51bluky59n2jr?cid=341) post it is necessary now, can you add it back? :sweat_smile:

**Comment by jjones-99** [comment]
Haha, all good! Reverted as of https://github.com/jjones-99/cs4500-sp2020-a1-part2-jones-tam/commit/1b59698414c52cdaf424a569934c4c3ef27f2787.
