### ISSUE TITLE
Equals method

### ISSUE THREAD

**Issue by chitalian** [jjones-99/cs4500-sp2020-a1-part2-jones-tam#7]
Can you implement and equals method on map?

```
    bool equals(Object *const obj)
```

**Comment by jjones-99** [comment]
Fixed in e211db2.

Map already had that method—inherited from Object—but now we specify some details of equality for clarity's sake.

**Comment by jjones-99** [comment]
Note we didn't add the signatures to `StrToStrMap`, as it inherits from `Map` and has the same functionality/equality details. Depending on your implementation, you may not even need to override `equals()` and `hash()` in `StrToStrMap`. But we don't know your implementation, so you do you.
